//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/-- SWORDPLAYFORIDIOTS --/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/-- SWORDPLAYFORIDIOTS --/Scripts/PlayerControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""SwordFightingForIdiots"",
            ""id"": ""26316f4a-69b2-4e2b-a00c-527c0c20ae09"",
            ""actions"": [
                {
                    ""name"": ""P1 Pivot"",
                    ""type"": ""Button"",
                    ""id"": ""c38a226d-b43f-4393-9c2b-d99f599a0116"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1 Stab"",
                    ""type"": ""Button"",
                    ""id"": ""bbb21898-6335-4ca6-a8d6-67a129544789"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1 Swing"",
                    ""type"": ""Button"",
                    ""id"": ""99256bd7-62a6-41cf-8d09-8307ee263b1e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2 Pivot"",
                    ""type"": ""Button"",
                    ""id"": ""93fe8bc7-da7a-4c61-997d-dfdf21538e2b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2 Stab"",
                    ""type"": ""Button"",
                    ""id"": ""80b23b54-1b0e-4582-9853-405414ba2b56"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2 Swing"",
                    ""type"": ""Button"",
                    ""id"": ""09f4d578-5d64-436d-bba9-9556c18cd663"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e55a6135-5b2f-48ff-b57e-01edbe3ef650"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyobard"",
                    ""action"": ""P1 Pivot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e467503-41d0-49d7-bc61-ba6cc6577578"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyobard"",
                    ""action"": ""P1 Stab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5db03261-3599-402b-9765-a6e9a1a42bdf"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyobard"",
                    ""action"": ""P1 Swing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b79f1bc7-502f-4a1f-9cc0-73dfd8804ab6"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyobard"",
                    ""action"": ""P2 Pivot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""838f7a94-6caa-423a-ba3e-503fd85742e2"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyobard"",
                    ""action"": ""P2 Stab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""387f8ce5-2ab9-43c4-9701-061d67f77dbc"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyobard"",
                    ""action"": ""P2 Swing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TreeGame"",
            ""id"": ""9bd9c751-a589-4307-b259-0d637a1efb10"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""62ab4f7d-f3fe-4b7a-b665-4490a8aa2e63"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""b6929bf4-36bd-497b-8559-f593b538ce0e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""40a6e0a8-595e-49e8-8d04-dc406be98dd2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bee2f628-5d51-4f6c-9265-db6c41faaeb0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyobard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e4a8052d-479e-4f55-9794-93e7b8f5f29b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bf68c99e-9af3-4f44-97d0-223a57edaeb3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyobard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a96d8fe5-54f7-49bb-8c89-57c871021bed"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyobard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""151864de-b2a8-4fac-b7fe-70b0f9b75bb7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyobard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyobard"",
            ""bindingGroup"": ""Keyobard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // SwordFightingForIdiots
        m_SwordFightingForIdiots = asset.FindActionMap("SwordFightingForIdiots", throwIfNotFound: true);
        m_SwordFightingForIdiots_P1Pivot = m_SwordFightingForIdiots.FindAction("P1 Pivot", throwIfNotFound: true);
        m_SwordFightingForIdiots_P1Stab = m_SwordFightingForIdiots.FindAction("P1 Stab", throwIfNotFound: true);
        m_SwordFightingForIdiots_P1Swing = m_SwordFightingForIdiots.FindAction("P1 Swing", throwIfNotFound: true);
        m_SwordFightingForIdiots_P2Pivot = m_SwordFightingForIdiots.FindAction("P2 Pivot", throwIfNotFound: true);
        m_SwordFightingForIdiots_P2Stab = m_SwordFightingForIdiots.FindAction("P2 Stab", throwIfNotFound: true);
        m_SwordFightingForIdiots_P2Swing = m_SwordFightingForIdiots.FindAction("P2 Swing", throwIfNotFound: true);
        // TreeGame
        m_TreeGame = asset.FindActionMap("TreeGame", throwIfNotFound: true);
        m_TreeGame_Move = m_TreeGame.FindAction("Move", throwIfNotFound: true);
        m_TreeGame_Jump = m_TreeGame.FindAction("Jump", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_SwordFightingForIdiots.enabled, "This will cause a leak and performance issues, PlayerControls.SwordFightingForIdiots.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_TreeGame.enabled, "This will cause a leak and performance issues, PlayerControls.TreeGame.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SwordFightingForIdiots
    private readonly InputActionMap m_SwordFightingForIdiots;
    private List<ISwordFightingForIdiotsActions> m_SwordFightingForIdiotsActionsCallbackInterfaces = new List<ISwordFightingForIdiotsActions>();
    private readonly InputAction m_SwordFightingForIdiots_P1Pivot;
    private readonly InputAction m_SwordFightingForIdiots_P1Stab;
    private readonly InputAction m_SwordFightingForIdiots_P1Swing;
    private readonly InputAction m_SwordFightingForIdiots_P2Pivot;
    private readonly InputAction m_SwordFightingForIdiots_P2Stab;
    private readonly InputAction m_SwordFightingForIdiots_P2Swing;
    /// <summary>
    /// Provides access to input actions defined in input action map "SwordFightingForIdiots".
    /// </summary>
    public struct SwordFightingForIdiotsActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public SwordFightingForIdiotsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "SwordFightingForIdiots/P1Pivot".
        /// </summary>
        public InputAction @P1Pivot => m_Wrapper.m_SwordFightingForIdiots_P1Pivot;
        /// <summary>
        /// Provides access to the underlying input action "SwordFightingForIdiots/P1Stab".
        /// </summary>
        public InputAction @P1Stab => m_Wrapper.m_SwordFightingForIdiots_P1Stab;
        /// <summary>
        /// Provides access to the underlying input action "SwordFightingForIdiots/P1Swing".
        /// </summary>
        public InputAction @P1Swing => m_Wrapper.m_SwordFightingForIdiots_P1Swing;
        /// <summary>
        /// Provides access to the underlying input action "SwordFightingForIdiots/P2Pivot".
        /// </summary>
        public InputAction @P2Pivot => m_Wrapper.m_SwordFightingForIdiots_P2Pivot;
        /// <summary>
        /// Provides access to the underlying input action "SwordFightingForIdiots/P2Stab".
        /// </summary>
        public InputAction @P2Stab => m_Wrapper.m_SwordFightingForIdiots_P2Stab;
        /// <summary>
        /// Provides access to the underlying input action "SwordFightingForIdiots/P2Swing".
        /// </summary>
        public InputAction @P2Swing => m_Wrapper.m_SwordFightingForIdiots_P2Swing;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_SwordFightingForIdiots; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="SwordFightingForIdiotsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(SwordFightingForIdiotsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="SwordFightingForIdiotsActions" />
        public void AddCallbacks(ISwordFightingForIdiotsActions instance)
        {
            if (instance == null || m_Wrapper.m_SwordFightingForIdiotsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SwordFightingForIdiotsActionsCallbackInterfaces.Add(instance);
            @P1Pivot.started += instance.OnP1Pivot;
            @P1Pivot.performed += instance.OnP1Pivot;
            @P1Pivot.canceled += instance.OnP1Pivot;
            @P1Stab.started += instance.OnP1Stab;
            @P1Stab.performed += instance.OnP1Stab;
            @P1Stab.canceled += instance.OnP1Stab;
            @P1Swing.started += instance.OnP1Swing;
            @P1Swing.performed += instance.OnP1Swing;
            @P1Swing.canceled += instance.OnP1Swing;
            @P2Pivot.started += instance.OnP2Pivot;
            @P2Pivot.performed += instance.OnP2Pivot;
            @P2Pivot.canceled += instance.OnP2Pivot;
            @P2Stab.started += instance.OnP2Stab;
            @P2Stab.performed += instance.OnP2Stab;
            @P2Stab.canceled += instance.OnP2Stab;
            @P2Swing.started += instance.OnP2Swing;
            @P2Swing.performed += instance.OnP2Swing;
            @P2Swing.canceled += instance.OnP2Swing;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="SwordFightingForIdiotsActions" />
        private void UnregisterCallbacks(ISwordFightingForIdiotsActions instance)
        {
            @P1Pivot.started -= instance.OnP1Pivot;
            @P1Pivot.performed -= instance.OnP1Pivot;
            @P1Pivot.canceled -= instance.OnP1Pivot;
            @P1Stab.started -= instance.OnP1Stab;
            @P1Stab.performed -= instance.OnP1Stab;
            @P1Stab.canceled -= instance.OnP1Stab;
            @P1Swing.started -= instance.OnP1Swing;
            @P1Swing.performed -= instance.OnP1Swing;
            @P1Swing.canceled -= instance.OnP1Swing;
            @P2Pivot.started -= instance.OnP2Pivot;
            @P2Pivot.performed -= instance.OnP2Pivot;
            @P2Pivot.canceled -= instance.OnP2Pivot;
            @P2Stab.started -= instance.OnP2Stab;
            @P2Stab.performed -= instance.OnP2Stab;
            @P2Stab.canceled -= instance.OnP2Stab;
            @P2Swing.started -= instance.OnP2Swing;
            @P2Swing.performed -= instance.OnP2Swing;
            @P2Swing.canceled -= instance.OnP2Swing;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SwordFightingForIdiotsActions.UnregisterCallbacks(ISwordFightingForIdiotsActions)" />.
        /// </summary>
        /// <seealso cref="SwordFightingForIdiotsActions.UnregisterCallbacks(ISwordFightingForIdiotsActions)" />
        public void RemoveCallbacks(ISwordFightingForIdiotsActions instance)
        {
            if (m_Wrapper.m_SwordFightingForIdiotsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="SwordFightingForIdiotsActions.AddCallbacks(ISwordFightingForIdiotsActions)" />
        /// <seealso cref="SwordFightingForIdiotsActions.RemoveCallbacks(ISwordFightingForIdiotsActions)" />
        /// <seealso cref="SwordFightingForIdiotsActions.UnregisterCallbacks(ISwordFightingForIdiotsActions)" />
        public void SetCallbacks(ISwordFightingForIdiotsActions instance)
        {
            foreach (var item in m_Wrapper.m_SwordFightingForIdiotsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SwordFightingForIdiotsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="SwordFightingForIdiotsActions" /> instance referencing this action map.
    /// </summary>
    public SwordFightingForIdiotsActions @SwordFightingForIdiots => new SwordFightingForIdiotsActions(this);

    // TreeGame
    private readonly InputActionMap m_TreeGame;
    private List<ITreeGameActions> m_TreeGameActionsCallbackInterfaces = new List<ITreeGameActions>();
    private readonly InputAction m_TreeGame_Move;
    private readonly InputAction m_TreeGame_Jump;
    /// <summary>
    /// Provides access to input actions defined in input action map "TreeGame".
    /// </summary>
    public struct TreeGameActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public TreeGameActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "TreeGame/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_TreeGame_Move;
        /// <summary>
        /// Provides access to the underlying input action "TreeGame/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_TreeGame_Jump;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_TreeGame; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="TreeGameActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(TreeGameActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="TreeGameActions" />
        public void AddCallbacks(ITreeGameActions instance)
        {
            if (instance == null || m_Wrapper.m_TreeGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TreeGameActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="TreeGameActions" />
        private void UnregisterCallbacks(ITreeGameActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TreeGameActions.UnregisterCallbacks(ITreeGameActions)" />.
        /// </summary>
        /// <seealso cref="TreeGameActions.UnregisterCallbacks(ITreeGameActions)" />
        public void RemoveCallbacks(ITreeGameActions instance)
        {
            if (m_Wrapper.m_TreeGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="TreeGameActions.AddCallbacks(ITreeGameActions)" />
        /// <seealso cref="TreeGameActions.RemoveCallbacks(ITreeGameActions)" />
        /// <seealso cref="TreeGameActions.UnregisterCallbacks(ITreeGameActions)" />
        public void SetCallbacks(ITreeGameActions instance)
        {
            foreach (var item in m_Wrapper.m_TreeGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TreeGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="TreeGameActions" /> instance referencing this action map.
    /// </summary>
    public TreeGameActions @TreeGame => new TreeGameActions(this);
    private int m_KeyobardSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyobardScheme
    {
        get
        {
            if (m_KeyobardSchemeIndex == -1) m_KeyobardSchemeIndex = asset.FindControlSchemeIndex("Keyobard");
            return asset.controlSchemes[m_KeyobardSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "SwordFightingForIdiots" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="SwordFightingForIdiotsActions.AddCallbacks(ISwordFightingForIdiotsActions)" />
    /// <seealso cref="SwordFightingForIdiotsActions.RemoveCallbacks(ISwordFightingForIdiotsActions)" />
    public interface ISwordFightingForIdiotsActions
    {
        /// <summary>
        /// Method invoked when associated input action "P1 Pivot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP1Pivot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P1 Stab" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP1Stab(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P1 Swing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP1Swing(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P2 Pivot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP2Pivot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P2 Stab" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP2Stab(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P2 Swing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP2Swing(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "TreeGame" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="TreeGameActions.AddCallbacks(ITreeGameActions)" />
    /// <seealso cref="TreeGameActions.RemoveCallbacks(ITreeGameActions)" />
    public interface ITreeGameActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
    }
}
